# Generated by Django 4.1.4 on 2023-01-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['club_name']},
        ),
        migrations.AlterModelOptions(
            name='clubstat',
            options={'ordering': ('-points', 'club')},
        ),
        migrations.AlterField(
            model_name='clubstat',
            name='goal_dif',
            field=models.IntegerField(default=0),
        ),
    ]
