# Generated by Django 4.1.4 on 2022-12-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstat',
            name='winner',
            field=models.CharField(max_length=100),
        ),
    ]
