# Generated by Django 4.1.4 on 2022-12-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_table', '0004_alter_matchstat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
