# Generated by Django 4.1.4 on 2023-01-01 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_table', '0005_alter_matchstat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubstat',
            name='club',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='league_table.club'),
        ),
    ]
